let ItemData = {
    'PlortSwitch_angler'    : { name: 'Plort switch: Angler', icon: 'iconPlortAngler', zIndex: 50 },
    'PlortSwitch_batty'     : { name: 'Plort switch: Batty', icon: 'iconPlortBatty', zIndex: 50 },
    'PlortSwitch_boom'      : { name: 'Plort switch: Boom', icon: 'iconPlortBoom', zIndex: 50 },
    'PlortSwitch_cotton'    : { name: 'Plort switch: Cotton', icon: 'iconPlortCotton', zIndex: 50 },
    'PlortSwitch_crystal'   : { name: 'Plort switch: Crystal', icon: 'iconPlortCrystal', zIndex: 50 },
    'PlortSwitch_dervish'   : { name: 'Plort switch: Dervish', icon: 'iconPlortDervish', zIndex: 50 },
    'PlortSwitch_fire'      : { name: 'Plort switch: Fire', icon: 'iconPlortFire', zIndex: 50 },
    'PlortSwitch_flutter'   : { name: 'Plort switch: Flutter', icon: 'iconPlortFlutter', zIndex: 50 },
    'PlortSwitch_gold'      : { name: 'Plort switch: Gold', icon: 'iconPlortGold', zIndex: 50 },
    'PlortSwitch_honey'     : { name: 'Plort switch: Honey', icon: 'iconPlortHoney', zIndex: 50 },
    'PlortSwitch_hunter'    : { name: 'Plort switch: Hunter', icon: 'iconPlortHunter', zIndex: 50 },
    'PlortSwitch_mosaic'    : { name: 'Plort switch: Mosaic', icon: 'iconPlortMosaic', zIndex: 50 },
    'PlortSwitch_phos'      : { name: 'Plort switch: Phosphor', icon: 'iconPlortPhosphor', zIndex: 50 },
    'PlortSwitch_pink'      : { name: 'Plort switch: Pink', icon: 'iconPlortPink', zIndex: 50 },
    'PlortSwitch_puddle'    : { name: 'Plort switch: Puddle', icon: 'iconPlortPuddle', zIndex: 50 },
    'PlortSwitch_quantum'   : { name: 'Plort switch: Quantum', icon: 'iconPlortQuantum', zIndex: 50 },
    'PlortSwitch_rad'       : { name: 'Plort switch: Rad', icon: 'iconPlortRad', zIndex: 50 },
    'PlortSwitch_ringtail'  : { name: 'Plort switch: Ringtail', icon: 'iconPlortRingtail', zIndex: 50 },
    'PlortSwitch_rock'      : { name: 'Plort switch: Rock', icon: 'iconPlortRock', zIndex: 50 },
    'PlortSwitch_saber'     : { name: 'Plort switch: Saber', icon: 'iconPlortSaber', zIndex: 50 },
    'PlortSwitch_tabby'     : { name: 'Plort switch: Tabby', icon: 'iconPlortTabby', zIndex: 50 },
    'PlortSwitch_tangle'    : { name: 'Plort switch: Tangle', icon: 'iconPlortTangle', zIndex: 50 },
    
    'treasurePod Rank1 TankGuardComponent'      : { name: 'Tank Guard Component', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconShopComponentVacTank' },
    'treasurePod Rank1 HeartModuleComponent'    : { name: 'Heart Module Component', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconShopComponentHeartCell' },
    'treasurePod Rank2 largepinkbonsai'         : { name: 'Large Pink Bonsai', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorLargePinkBonsai' },
    'treasurePod Rank2 rockfragments'           : { name: 'Rock Fragments', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorRockFragments' },
    'treasurePod Rank3 slimestage'              : { name: 'Slime Stage', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconCurioSlimeStage' },
    'treasurePod Rank1 hydroturret'             : { name: 'Hydro Turret', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconGadgetHydroTurret' },
    'treasurePod Rank1 pinkwarpdepot'           : { name: 'Pink Warp Depot', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconGadgetWarpDepotPink' },
    'treasurePod Rank2 goldpetal'               : { name: 'Gold Petal', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorGoldpetalFlowers' },
    'treasurePod Rank2 smallboulder'            : { name: 'Small Boulder', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorSmallBoulder' },
    'treasurePod Rank1 emeraldcypresscluster'   : { name: 'Emerald Cypress Cluster', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorEmeraldCypressCluster' },
    'treasurePod Rank1 medstation'              : { name: 'Med Station', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconGadgetMedStation' },
    'treasurePod Rank2 PowerCoreComponent'      : { name: 'Power Core Component', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconShopComponentInjectorModule' },
    'treasurePod Rank2 emeraldcypress'          : { name: 'Emerald Cypress', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorEmeraldCypress' },
    'treasurePod Rank3 overjoyedstatue'         : { name: 'Overjoyed Statue', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorOverjoyedStatue' },
     
     'treasurePod Rank1 azuremangrove'          : { name: 'Azure Mangrove', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorAzureMangrove' },
     'treasurePod Rank1 azureshrubs'            : { name: 'Azure Shrubs', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorAzureShrubs' },
     'treasurePod Rank1 cavepillar'             : { name: 'Cave Pillar', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorCavePillar' },
     'treasurePod Rank1 coastalrockpillar'      : { name: 'Coastal Rock Pillar', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorCoastalRockPillar' },
     'treasurePod Rank1 pinkglowshroom'         : { name: 'Pink Glow Shroom', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorPinkGlowShrooms' },
     'treasurePod Rank1 PowerCoreComponent'     : { name: 'Power Core Component', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconShopPower01' },
     'treasurePod Rank1 roottangle'             : { name: 'Root Tangle', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorRootTangle' },
     'treasurePod Rank1 slimebaitveggie'        : { name: 'Slime Bait Veggie', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconGadgetBaitCarrot' },
     'treasurePod Rank1 springpad'              : { name: 'Spring Pad', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconGadgetSpringPad' },
     'treasurePod Rank1 stalagmitecluster'      : { name: 'Stalagmite Cluster', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorStalagmiteCluster' },
     'treasurePod Rank1 starbloom'              : { name: 'Starbloom', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorStarbloomFlowers' },
     'treasurePod Rank1 tallvioletswirlshroom'  : { name: 'Tall Violet Swirlshroom', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorTallVioletSwirlShroom' },
     'treasurePod Rank1 TankBoosterComponent'   : { name: 'Tank Booster Component', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconShopTankBooster01' },
     'treasurePod Rank1 TankGuardComponent'     : { name: 'Tank Guard Component', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconShopTankGuard01' },
     'treasurePod Rank1 violetwarpdepot'        : { name: 'Violet Warpdepot', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconGadgetWarpDepotViolet' },
     'treasurePod Rank2 azuregrass'             : { name: 'Azure Grass', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorAzureGrass' },
     'treasurePod Rank2 cheerfulstatue'         : { name: 'Cheerful Statue', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorCheerfulStatue' },
     'treasurePod Rank2 DashBootComponent'      : { name: 'Dash Boot Component', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconShopComponentDashBootModule' },
     'treasurePod Rank2 gordosnarenovice'       : { name: 'Gordo Snare Novice', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconGadgetGordoSnareNovice' },
     'treasurePod Rank2 rockcluster'            : { name: 'Rock Cluster', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorRockCluster' },
     'treasurePod Rank2 TankGuardComponent'     : { name: 'Tank Guard Component', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconShopComponentVacTank' },
     'treasurePod Rank3 end teleporterstrand'   : { name: 'Teleporter Strand', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconGadgetTeleportStarlightStrand' },
     'treasurePod Rank3 sharpboulder'           : { name: 'Sharp Boulder', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorSharpBoulder' },
     'treasurePod Rank3 tallpinkcoralcolumns'   : { name: 'Tall Pink Coral Columns', icon: 'iconTreasurePod', zIndex: 50, hoverIcon: 'iconDecorTallPinkCoralColumns' },
    
     'gordo'                : { name: 'Gordo: ???', icon: 'iconGordoPink', zIndex: 150 },
     'nodeSlimeGold'        : { name: 'Slime Spawn: Gold', icon: 'iconSlimeGold', zIndex: 100 },
     'slimeSpawn:Puddle'    : { name: 'Slime Spawn: Puddle', icon: 'iconSlimePuddle', zIndex: 100 },
     'slimeSpawn:Angler'    : { name: 'Slime Spawn: Angler', icon: 'iconSlimeAngler', zIndex: 100 },
     'slimeSpawn:Feral'     : { name: 'Slime Spawn: Feral', icon: 'iconFeralPedia', zIndex: 100 },
     'slimeSpawn:Cotton'    : { name: 'Slime Spawn: Cotton', icon: 'iconSlimeCotton', zIndex: 100 },
     'slimeSpawn:Flutter'   : { name: 'Slime Spawn: Flutter', icon: 'iconSlimeFlutter', zIndex: 100 },
     'nodeRingtailSpawnLoc' : { name: 'Slime Spawn: Ringtail', icon: 'iconSlimeRingtail', zIndex: 100 },
    
     'Rainbow Activation'   : { name: 'Portal Activation', icon: 'iconSSWarpTech', zIndex: 150 },
     'researchDrone'        : { name: 'Research Drone', icon: 'iconDrone', zIndex: 150 },
     'nodeMapEntry'         : { name: 'Reveal Map', icon: 'iconChromaPack_26', zIndex: 150 },
     'gadgetRefineryLink'   : { name: 'Gadget: Refinery Link', icon: 'iconRefineryLink', zIndex: 150 },
    
     'treePogo'         : { name: 'Pogo', icon: 'iconFruitPogo', zIndex: 100 },
     'treeCuberry'      : { name: 'Cuberry', icon: 'iconFruitCuberry', zIndex: 100 },
     'treeMango'        : { name: 'Mango', icon: 'iconFruitMango', zIndex: 100 },
     'treeMoonflower'   : { name: 'Moonflower', icon: 'iconCategoryNectar', zIndex: 100 },
    
     'patchEmpty'   : { name: 'Empty Plot', icon: 'iconPatchEmpty', zIndex: 100 },
     'patchCarrot'  : { name: 'Carrots', icon: 'iconVeggieCarrot', zIndex: 100 },
     'patchLettuce' : { name: 'Lettuce', icon: 'iconVeggieLettuce', zIndex: 100 },
    
     'Hive'     : { name: 'Bee Hive', icon: 'iconCraftWildHoney', zIndex: 100 },
     'Ore'       : { name: 'Ore', icon: 'lockedIcon', zIndex: 100 },
     'Spout'     : { name: 'Spout', icon: 'lockedIcon', zIndex: 100 },
     'spoutSand'     : { name: 'Spout', icon: 'iconCraftSilkySand', zIndex: 100 },
     'spoutOil'     : { name: 'Spout', icon: 'iconCraftPrimordyOil', zIndex: 100 },
     'spoutBrine'     : { name: 'Spout', icon: 'iconCraftDeepBrine', zIndex: 100 },
    }